# tasks for Debian Familly
---
- name: add apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ xtradb_repo_gpgkey }}"

- name: repository installation
  apt_repository:
    filename: "{{ xtradb_repo_filename }}" 
    repo: "{{ xtradb_repo_baseurl }}"
    #update_cache: yes

- name: update cache
  apt:
    update_cache: yes
  changed_when: false
...
