---
- name: Copy clustercheck script
  copy:
    src: ../files/clustercheck
    dest: /usr/bin/
    owner: root
    group: root
    mode: 0755
    
- name: Install xinetd for cluster stats check
  package:
    name: xinetd
    state: present

- name: Configure mysqlchk as a service
  lineinfile:
    path: /etc/services
    regexp: '^mysqlchk'
    line: mysqlchk 9200/tcp

- name: Copying mysqlchk conf file
  template:
    src: ../templates/mysqlchk.j2
    dest: /etc/xinetd.d/mysqlchk
    owner: root
    group: root
    mode: 0644
  
- name: Start and reload xinetd for cluster stats check
  service:
    name: xinetd
    state: reloaded
    enabled: yes

- name: MySQL Exporter | Download Binary
  get_url:
    url: "https://github.com/prometheus/mysqld_exporter/releases/download/v0.12.1/mysqld_exporter-0.12.1.linux-amd64.tar.gz"
    dest: "/tmp/mysqld_exporter-0.12.1.linux-amd64.tar.gz"

- name: MySQL Exporter | Extract Binary
  unarchive:
    src: "/tmp/mysqld_exporter-0.12.1.linux-amd64.tar.gz"
    dest: /usr/local/bin/mysqld_exporter/
    remote_src: true

- name: MySQL Exporter  | Systemd Service
  template:
    src: mysqld_exporter.service.j2
    dest: /etc/systemd/system/mysqld_exporter.service

- name: MySQL Exporter | Generate connection string
  template: 
    src: mysqld_exporter.cnf.j2
    dest: /usr/local/bin/mysqld_exporter/
  
- name: MySQL Exporter | Start Service
  systemd:
    daemon_reload: true
    name: mysqld_exporter
    enabled: true
    state: started
  tags: mysqld_exporter